import typing
from . import cfg
from abc import ABC

def noauth(cmd: typing.Callable[..., typing.Any]) -> typing.Callable[..., typing.Any]: ...

class Cmd:
    s: str
    def __init__(self, s: str, cfg: cfg.Cfg) -> None: ...
    def remove_token(self, token: str) -> None: ...
    def next_token(self) -> Union[str, None]: ...
    def __iter__(self) -> Cmd: ...
    def __next__(self) -> str: ...
    def __bool__(self) -> bool: ...

class CmdIndex(ABC):
    @property
    def cmds(self) -> dict[str, typing.Any]: ...
